apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo17
  labels:
    backstage.io/kubernetes-id: argo17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo17
  template:
    metadata:
      labels:
        app: argo17
        backstage.io/kubernetes-id: argo17
    spec:
      containers:
        - name: argo17
          image: chaitanyapandeygspann/argo17:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000