apiVersion: apps/v1
kind: Deployment
metadata:
  name: argotest25
  labels:
    backstage.io/kubernetes-id: argotest25
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argotest25
  template:
    metadata:
      labels:
        app: argotest25
        backstage.io/kubernetes-id: argotest25
    spec:
      containers:
        - name: argotest25
          image: chaitanyapandeygspann/argotest25:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000