apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo12
  labels:
    backstage.io/kubernetes-id: argo12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo12
  template:
    metadata:
      labels:
        app: argo12
        backstage.io/kubernetes-id: argo12
    spec:
      containers:
        - name: argo12
          image: chaitanyapandeygspann/argo12:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000