apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo3
  labels:
    backstage.io/kubernetes-id: argo3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo3
  template:
    metadata:
      labels:
        app: argo3
        backstage.io/kubernetes-id: argo3
    spec:
      containers:
        - name: argo3
          image: chaitanyapandeygspann/argo3:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000