apiVersion: v1
kind: Service
metadata:
  name: argo18
spec:
  selector:
    app: argo18
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: argo18-ingress
# spec:
#   ingressClassName: gce
#   rules:
#   - host: argo18.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: argo18
#             port:
#               number: 80
