apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo9
  labels:
    backstage.io/kubernetes-id: argo9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo9
  template:
    metadata:
      labels:
        app: argo9
        backstage.io/kubernetes-id: argo9
    spec:
      containers:
        - name: argo9
          image: chaitanyapandeygspann/argo9:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000