apiVersion: apps/v1
kind: Deployment
metadata:
  name: argotest13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argotest13
  template:
    metadata:
      labels:
        app: argotest13
    spec:
      containers:
        - name: argotest13
          image: chaitanyapandeygspann/argotest13:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000