apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1
  labels:
    backstage.io/kubernetes-id: demo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo1
  template:
    metadata:
      labels:
        app: demo1
        backstage.io/kubernetes-id: demo1
    spec:
      containers:
        - name: demo1
          image: chaitanyapandeygspann/demo1:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000