apiVersion: v1
kind: Service
metadata:
  name: demo1
spec:
  selector:
    app: demo1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: demo1-ingress
# spec:
#   ingressClassName: gce
#   rules:
#   - host: demo1.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: demo1
#             port:
#               number: 80
