apiVersion: v1
kind: Service
metadata:
  name: test-demo-1
spec:
  selector:
    app: test-demo-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: test-demo-1-ingress
# spec:
#   ingressClassName: gce
#   rules:
#   - host: test-demo-1.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: test-demo-1
#             port:
#               number: 80
