apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2
  labels:
    backstage.io/kubernetes-id: service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-2
  template:
    metadata:
      labels:
        app: service-2
        backstage.io/kubernetes-id: service-2
    spec:
      containers:
        - name: service-2
          image: chaitanyapandeygspann/service-2:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000