apiVersion: apps/v1
kind: Deployment
metadata:
  name: jk7test8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jk7test8
  template:
    metadata:
      labels:
        app: jk7test8
    spec:
      containers:
        - name: jk7test8
          image: chaitanyapandeygspann/jk7test8:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000