apiVersion: apps/v1
kind: Deployment
metadata:
  name: argotest12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argotest12
  template:
    metadata:
      labels:
        app: argotest12
    spec:
      containers:
        - name: argotest12
          image: chaitanyapandeygspann/argotest12:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000