apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdemo18feb-1
  labels:
    backstage.io/kubernetes-id: testdemo18feb-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testdemo18feb-1
  template:
    metadata:
      labels:
        app: testdemo18feb-1
        backstage.io/kubernetes-id: testdemo18feb-1
    spec:
      containers:
        - name: testdemo18feb-1
          image: chaitanyapandeygspann/testdemo18feb-1:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000