apiVersion: apps/v1
kind: Deployment
metadata:
  name: jk7test5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jk7test5
  template:
    metadata:
      labels:
        app: jk7test5
    spec:
      containers:
        - name: jk7test5
          image: chaitanyapandeygspann/jk7test5:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000