apiVersion: v1
kind: Service
metadata:
  name: argo-integration-alpha
spec:
  selector:
    app: argo-integration-alpha
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: argo-integration-alpha-ingress
# spec:
#   ingressClassName: gce
#   rules:
#   - host: argo-integration-alpha.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: argo-integration-alpha
#             port:
#               number: 80
