apiVersion: apps/v1
kind: Deployment
metadata:
  name: jk7test7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jk7test7
  template:
    metadata:
      labels:
        app: jk7test7
    spec:
      containers:
        - name: jk7test7
          image: chaitanyapandeygspann/jk7test7:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000