apiVersion: apps/v1
kind: Deployment
metadata:
  name: argotest26
  labels:
    backstage.io/kubernetes-id: argotest26
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argotest26
  template:
    metadata:
      labels:
        app: argotest26
        backstage.io/kubernetes-id: argotest26
    spec:
      containers:
        - name: argotest26
          image: chaitanyapandeygspann/argotest26:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000