apiVersion: apps/v1
kind: Deployment
metadata:
  name: jk7test3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jk7test3
  template:
    metadata:
      labels:
        app: jk7test3
    spec:
      containers:
        - name: jk7test3
          image: chaitanyapandeygspann/jk7test3:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000