apiVersion: apps/v1
kind: Deployment
metadata:
  name: jk7test4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jk7test4
  template:
    metadata:
      labels:
        app: jk7test4
    spec:
      containers:
        - name: jk7test4
          image: chaitanyapandeygspann/jk7test4:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000