apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo8
  labels:
    backstage.io/kubernetes-id: argo8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo8
  template:
    metadata:
      labels:
        app: argo8
        backstage.io/kubernetes-id: argo8
    spec:
      containers:
        - name: argo8
          image: chaitanyapandeygspann/argo8:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000