apiVersion: apps/v1
kind: Deployment
metadata:
  name: argotest14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argotest14
  template:
    metadata:
      labels:
        app: argotest14
    spec:
      containers:
        - name: argotest14
          image: chaitanyapandeygspann/argotest14:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000