apiVersion: v1
kind: Service
metadata:
  name: testdemo18feb-2
spec:
  selector:
    app: testdemo18feb-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP