apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo1
  labels:
    backstage.io/kubernetes-id: argo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo1
  template:
    metadata:
      labels:
        app: argo1
        backstage.io/kubernetes-id: argo1
    spec:
      containers:
        - name: argo1
          image: chaitanyapandeygspann/argo1:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000