apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo14
  labels:
    backstage.io/kubernetes-id: argo14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo14
  template:
    metadata:
      labels:
        app: argo14
        backstage.io/kubernetes-id: argo14
    spec:
      containers:
        - name: argo14
          image: chaitanyapandeygspann/argo14:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000