apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-demo-3
  labels:
    backstage.io/kubernetes-id: test-demo-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-demo-3
  template:
    metadata:
      labels:
        app: test-demo-3
        backstage.io/kubernetes-id: test-demo-3
    spec:
      containers:
        - name: test-demo-3
          image: chaitanyapandeygspann/test-demo-3:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000