# apiVersion: v1
# kind: Service
# metadata:
#   name: argo16
# spec:
#   selector:
#     app: argo16
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#   type: ClusterIP


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo16-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: "app-cert"
spec:
  rules:
  - host: argo16.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argo16
            port:
              number: 80