apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo2
  labels:
    backstage.io/kubernetes-id: argo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo2
  template:
    metadata:
      labels:
        app: argo2
        backstage.io/kubernetes-id: argo2
    spec:
      containers:
        - name: argo2
          image: chaitanyapandeygspann/argo2:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000