apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo7
  labels:
    backstage.io/kubernetes-id: argo7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo7
  template:
    metadata:
      labels:
        app: argo7
        backstage.io/kubernetes-id: argo7
    spec:
      containers:
        - name: argo7
          image: chaitanyapandeygspann/argo7:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000