apiVersion: apps/v1
kind: Deployment
metadata:
  name: argotest15
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argotest15
  template:
    metadata:
      labels:
        app: argotest15
    spec:
      containers:
        - name: argotest15
          image: chaitanyapandeygspann/argotest15:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000